version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.29.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.24.0
    - 2.25.0
    - 2.25.1
    - 2.25.2
    - 2.26.0
    - 2.27.0
    - 2.27.1
    - 2.28.0
    - 2.28.1
    - 2.28.2
    - 2.28.3
    - 2.28.4
    - 2.28.5
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.0
    - 2.30.1
    - 2.30.2
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.0
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.36.0
    - 2.37.0
    - 2.37.1
    - 2.37.2
  - dependency-name: cspell
    versions:
    - 5.2.4
    - 5.3.0
    - 5.3.1
    - 5.3.10
    - 5.3.11
    - 5.3.2
    - 5.3.3
    - 5.3.4
    - 5.3.5
    - 5.3.6
    - 5.3.7
    - 5.3.8
    - 5.3.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
  commit-message:
    prefix: chore
    include: scope
