env:
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
  - functional
overrides:
  - env:
      jest: true
    files:
      - __mocks__/**/*.ts
      - src/**/*.spec.ts
      - test/**/*.ts
    rules:
      'functional/no-return-void': off
      'functional/functional-parameters': off
      'functional/no-expression-statement': off
      '@typescript-eslint/no-magic-numbers': off
      '@typescript-eslint/typedef': warn
      'max-lines': 0
      'max-lines-per-function': off
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'
rules:
  functional/no-try-statement: off
